import type { CohortSummary, FacultyDashboardData, Student, WhatIfInput, WhatIfResult } from './types';

export const defaultWhatIfInput: WhatIfInput = {
  attendancePct: 88,
  assessmentScore: 78,
  assignmentScore: 72,
};

export const student: Student = {
  id: 'st-101',
  name: 'Aanya Sharma',
  className: 'Class 11-A',
  email: 'aanya.sharma@edupulse.ai',
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
  gpa: 8.7,
  attendancePct: 89,
  riskLevel: 'low',
  riskScore: 26,
  performanceScore: 84,
  subjects: [
    { subject: 'Mathematics', currentScore: 86, trend: 'up' },
    { subject: 'Physics', currentScore: 79, trend: 'up' },
    { subject: 'Chemistry', currentScore: 74, trend: 'flat' },
    { subject: 'English', currentScore: 91, trend: 'up' },
    { subject: 'Biology', currentScore: 68, trend: 'down' },
  ],
  weeklyTrend: [
    { week: 'W1', score: 68 },
    { week: 'W2', score: 71 },
    { week: 'W3', score: 74 },
    { week: 'W4', score: 72 },
    { week: 'W5', score: 79 },
    { week: 'W6', score: 82 },
    { week: 'W7', score: 85 },
  ],
  upcomingExams: [
    { subject: 'Physics', date: '2026-08-29' },
    { subject: 'Chemistry', date: '2026-09-02' },
    { subject: 'Mathematics', date: '2026-09-05' },
  ],
  recommendations: [
    {
      id: 'rec-1',
      title: 'Protect current momentum',
      priority: 'medium',
      text: 'Keep revision blocks consistent during the next two weeks to protect this strong chemistry momentum.',
      action: 'Schedule two 30-minute revision blocks this week.',
    },
    {
      id: 'rec-2',
      title: 'Biology catch-up',
      priority: 'high',
      text: 'Biology needs a focused review cycle before the upcoming exam. Short, regular recap sessions are more effective than one large session.',
      action: 'Use one daily biology recap session before the next class.',
    },
    {
      id: 'rec-3',
      title: 'Assignment consistency',
      priority: 'low',
      text: 'Attendance remains healthy, but continuing to submit assignments on time will push the model risk estimate lower.',
      action: 'Submit the next assignment before the weekend deadline.',
    },
  ],
  riskFactors: [
    {
      id: 'risk-1',
      label: 'Biology performance',
      impact: 'negative',
      magnitude: 42,
      detail: 'Biology has dipped in the last two weeks and adds a small drag to the overall projection.',
    },
    {
      id: 'risk-2',
      label: 'Study consistency',
      impact: 'positive',
      magnitude: 58,
      detail: 'Regular revision across maths and English keeps the overall prediction stable and improving.',
    },
  ],
  prediction: {
    studentId: 'st-101',
    predictedScore: 84,
    riskLevel: 'low',
    confidence: 0.86,
    summary: 'The model predicts a stable academic trajectory with a low-risk pattern if current effort remains steady.',
    generatedAt: '2026-08-23T09:00:00Z',
    riskFactors: [
      {
        id: 'risk-1',
        label: 'Biology performance',
        impact: 'negative',
        magnitude: 42,
        detail: 'Biology remains the main subject pressure point in the current forecast.',
      },
      {
        id: 'risk-2',
        label: 'Study consistency',
        impact: 'positive',
        magnitude: 58,
        detail: 'Current revision consistency is helping the student stay in the low-risk band.',
      },
    ],
  },
};

export const mentorStudents: Student[] = [
  student,
  {
    id: 'st-204',
    name: 'Rohan Iyer',
    className: 'Class 10-B',
    email: 'rohan.iyer@edupulse.ai',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    gpa: 7.8,
    attendancePct: 77,
    riskLevel: 'medium',
    riskScore: 48,
    performanceScore: 71,
    subjects: [
      { subject: 'Mathematics', currentScore: 72, trend: 'up' },
      { subject: 'Physics', currentScore: 69, trend: 'flat' },
      { subject: 'Chemistry', currentScore: 78, trend: 'up' },
      { subject: 'English', currentScore: 83, trend: 'flat' },
      { subject: 'Biology', currentScore: 64, trend: 'down' },
    ],
    weeklyTrend: [
      { week: 'W1', score: 66 },
      { week: 'W2', score: 67 },
      { week: 'W3', score: 70 },
      { week: 'W4', score: 72 },
      { week: 'W5', score: 70 },
      { week: 'W6', score: 76 },
      { week: 'W7', score: 78 },
    ],
    upcomingExams: [
      { subject: 'Biology', date: '2026-08-30' },
      { subject: 'Physics', date: '2026-09-04' },
    ],
    recommendations: [
      {
        id: 'rec-4',
        title: 'Attendance support',
        priority: 'high',
        text: 'Attendance needs a steady increase to improve continuity in conceptual reading.',
        action: 'Introduce a check-in routine before the next two periods.',
      },
      {
        id: 'rec-5',
        title: 'Biology checkpoint',
        priority: 'medium',
        text: 'Add one biology checkpoint before exam day to recover recent confidence dips.',
        action: 'Schedule a short review quiz on Thursday.',
      },
    ],
    riskFactors: [
      {
        id: 'risk-3',
        label: 'Attendance consistency',
        impact: 'negative',
        magnitude: 51,
        detail: 'Lower attendance is reducing continuity in workshop-heavy topics.',
      },
      {
        id: 'risk-4',
        label: 'Science improvement',
        impact: 'positive',
        magnitude: 49,
        detail: 'Chemistry performance is improving and helping stabilize the forecast.',
      },
    ],
    prediction: {
      studentId: 'st-204',
      predictedScore: 71,
      riskLevel: 'medium',
      confidence: 0.74,
      summary: 'The model sees a mixed trend, with chemistry support offset by a slipping biology signal.',
      generatedAt: '2026-08-23T09:10:00Z',
      riskFactors: [
        {
          id: 'risk-3',
          label: 'Attendance consistency',
          impact: 'negative',
          magnitude: 51,
          detail: 'Lower attendance is causing uneven coverage of key concepts.',
        },
        {
          id: 'risk-4',
          label: 'Science improvement',
          impact: 'positive',
          magnitude: 49,
          detail: 'Chemistry is trending upward and reducing some risk pressure.',
        },
      ],
    },
  },
  {
    id: 'st-315',
    name: 'Meera Patel',
    className: 'Class 9-C',
    email: 'meera.patel@edupulse.ai',
    avatarUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=200&q=80',
    gpa: 6.9,
    attendancePct: 71,
    riskLevel: 'high',
    riskScore: 72,
    performanceScore: 64,
    subjects: [
      { subject: 'Mathematics', currentScore: 58, trend: 'down' },
      { subject: 'Physics', currentScore: 63, trend: 'flat' },
      { subject: 'Chemistry', currentScore: 66, trend: 'down' },
      { subject: 'English', currentScore: 74, trend: 'flat' },
      { subject: 'Biology', currentScore: 57, trend: 'down' },
    ],
    weeklyTrend: [
      { week: 'W1', score: 61 },
      { week: 'W2', score: 59 },
      { week: 'W3', score: 60 },
      { week: 'W4', score: 62 },
      { week: 'W5', score: 58 },
      { week: 'W6', score: 63 },
      { week: 'W7', score: 64 },
    ],
    upcomingExams: [
      { subject: 'Mathematics', date: '2026-08-28' },
      { subject: 'Physics', date: '2026-09-03' },
      { subject: 'Chemistry', date: '2026-09-07' },
    ],
    recommendations: [
      {
        id: 'rec-6',
        title: 'Intervention priority',
        priority: 'high',
        text: 'Attendance support and a daily homework plan should be the first intervention.',
        action: 'Book a focused support session with the science mentor.',
      },
      {
        id: 'rec-7',
        title: 'Short revision blocks',
        priority: 'medium',
        text: 'Short, consistent revision sessions are more effective than longer irregular bursts.',
        action: 'Shift to four 20-minute review blocks per day.',
      },
    ],
    riskFactors: [
      {
        id: 'risk-5',
        label: 'Attendance gaps',
        impact: 'negative',
        magnitude: 64,
        detail: 'Frequent attendance gaps are reducing exposure to recent instruction.',
      },
      {
        id: 'risk-6',
        label: 'Retention trend',
        impact: 'negative',
        magnitude: 57,
        detail: 'Several core subjects show a downward learning trend over the last month.',
      },
    ],
    prediction: {
      studentId: 'st-315',
      predictedScore: 64,
      riskLevel: 'high',
      confidence: 0.8,
      summary: 'The model projects a high-risk pattern unless attendance and revision routines improve in the next cycle.',
      generatedAt: '2026-08-23T09:20:00Z',
      riskFactors: [
        {
          id: 'risk-5',
          label: 'Attendance gaps',
          impact: 'negative',
          magnitude: 64,
          detail: 'This is the main driver behind the current high-risk output.',
        },
        {
          id: 'risk-6',
          label: 'Retention trend',
          impact: 'negative',
          magnitude: 57,
          detail: 'The student is losing ground across several core topics.',
        },
      ],
    },
  },
  {
    id: 'st-422',
    name: 'Kabir Singh',
    className: 'Class 12-B',
    email: 'kabir.singh@edupulse.ai',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    gpa: 8.2,
    attendancePct: 92,
    riskLevel: 'low',
    riskScore: 21,
    performanceScore: 87,
    subjects: [
      { subject: 'Mathematics', currentScore: 88, trend: 'up' },
      { subject: 'Physics', currentScore: 80, trend: 'up' },
      { subject: 'Chemistry', currentScore: 84, trend: 'up' },
      { subject: 'English', currentScore: 86, trend: 'flat' },
      { subject: 'Biology', currentScore: 82, trend: 'up' },
    ],
    weeklyTrend: [
      { week: 'W1', score: 76 },
      { week: 'W2', score: 79 },
      { week: 'W3', score: 81 },
      { week: 'W4', score: 80 },
      { week: 'W5', score: 83 },
      { week: 'W6', score: 85 },
      { week: 'W7', score: 87 },
    ],
    upcomingExams: [
      { subject: 'Biology', date: '2026-09-01' },
      { subject: 'English', date: '2026-09-06' },
    ],
    recommendations: [
      {
        id: 'rec-8',
        title: 'Maintain momentum',
        priority: 'low',
        text: 'Continue the current preparation rhythm and add a confidence review before paper submissions.',
        action: 'Keep the current planner and review before every mock paper.',
      },
      {
        id: 'rec-9',
        title: 'Stretch goal',
        priority: 'medium',
        text: 'A stretch goal of higher physics practical scores would maintain the strong performance trend.',
        action: 'Add one extra physics practical review before the next lab cycle.',
      },
    ],
    riskFactors: [
      {
        id: 'risk-7',
        label: 'Strong consistency',
        impact: 'positive',
        magnitude: 71,
        detail: 'The student is staying consistent across both revision and attendance.',
      },
      {
        id: 'risk-8',
        label: 'Minor retention risk',
        impact: 'negative',
        magnitude: 24,
        detail: 'Only a small risk remains in practical-heavy subjects if the routine slips.',
      },
    ],
    prediction: {
      studentId: 'st-422',
      predictedScore: 87,
      riskLevel: 'low',
      confidence: 0.9,
      summary: 'The model expects the student to remain in a low-risk band as long as the current routine is maintained.',
      generatedAt: '2026-08-23T09:30:00Z',
      riskFactors: [
        {
          id: 'risk-7',
          label: 'Strong consistency',
          impact: 'positive',
          magnitude: 71,
          detail: 'Model confidence remains high due to stable attendance and improving results.',
        },
        {
          id: 'risk-8',
          label: 'Minor retention risk',
          impact: 'negative',
          magnitude: 24,
          detail: 'A small practical-performance dip remains the only notable caution.',
        },
      ],
    },
  },
];

export const cohortSummary: CohortSummary = {
  totalStudents: mentorStudents.length,
  highRiskCount: mentorStudents.filter((entry) => entry.riskLevel === 'high').length,
  avgGpa: Number(
    (mentorStudents.reduce((sum, current) => sum + current.gpa, 0) / mentorStudents.length).toFixed(1),
  ),
  riskDistribution: [
    { level: 'low', count: 2 },
    { level: 'medium', count: 1 },
    { level: 'high', count: 1 },
  ],
};

export const facultyDashboard: FacultyDashboardData = {
  totalStudents: mentorStudents.length,
  highRiskCount: 1,
  mediumRiskCount: 1,
  lowRiskCount: 2,
  riskDistribution: [
    { level: 'low', count: 2 },
    { level: 'medium', count: 1 },
    { level: 'high', count: 1 },
  ],
  students: mentorStudents.map((studentEntry) => ({
    id: studentEntry.id,
    name: studentEntry.name,
    className: studentEntry.className,
    email: studentEntry.email,
    gpa: studentEntry.gpa,
    attendancePct: studentEntry.attendancePct,
    riskLevel: studentEntry.riskLevel,
    riskScore: studentEntry.riskScore,
    lastUpdated: '2026-08-23',
    priority: studentEntry.riskLevel === 'high' ? 'high' : studentEntry.riskLevel === 'medium' ? 'medium' : 'low',
  })),
  interventions: [
    {
      id: 'int-1',
      title: 'Priority: Meera Patel',
      priority: 'high',
      text: 'High-risk focus with attendance and retrieval support recommended for the next review cycle.',
      action: 'Schedule a mentor check-in within 48 hours.',
    },
    {
      id: 'int-2',
      title: 'Rohan Iyer check-in',
      priority: 'medium',
      text: 'Biology and attendance continue to influence the model risk trend. A short support plan is recommended.',
      action: 'Create an attendance recovery plan.',
    },
  ],
  summary: 'The cohort is stable overall, but three students remain signal-sensitive in science and attendance.',
};

export const whatIfPreview: WhatIfResult = {
  currentScore: 84,
  simulatedScore: 90,
  predictedRisk: 'low',
  deltaFromCurrent: 6,
  scenarioLabel: 'Model-simulated scenario',
  explanation: 'This result is a model-simulated estimate based on improved attendance, assessment completion, and assignment consistency.',
};
